inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20221010105020_devise_create_accounts.rb'

Style/Documentation:
  Enabled: false
