# `rubocop --auto-gen-config`
# on 2022-10-10 10:33:23 UTC using RuboCop version 1.36.0.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: TreatCommentsAsGroupSeparators, ConsiderPunctuation, Include.
# Include: **/*.gemfile, **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 2
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/requests/projects_spec.rb'
    - 'spec/requests/tasks_spec.rb'

# Offense count: 6
Rails/I18nLocaleTexts:
  Exclude:
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/tasks_controller.rb'
